os: osx
language: node_js
node_js:
- '6'
before_install:
- brew update && brew install git-lfs
- git lfs install
install:
- npm install
before_script:
- git lfs pull
script:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: BqMuIaKGO02xRQCfsmPLD73AzL0dxMYKikvZ7VTDlU3IOlVNS2WA/6VAN4y6eZ/N1AleOV3gpljL9aeEeddy07xms27GP2pTwxBSvqE+MOtf8+QlJeM98Yw3Gyqlii5Z688Wlfd8rHHTEiByR2roNTptpR5S4ruQj/xKXEEiq26OFsSSLrTe5Us2kCDwoFndXZHE/Ps3ZVPBWD/9rMLX1G5arFjolo9PofYVu2YJQDGfsuajdKtDB8ASYTX/YtYCF4Bxvb/BfCH05sfSaonE/YYgCyVkyktQnLGq7LrHssZTMsK6EyzUrE7qGfoafj579GC75ygLpBVxlfRJhjpXizxVR3o7P3cFhizTYMuU0sQLYWvUHGkO1FAGX6HsSr68SyjutNs/Bdxgakn4Uz494Qdri4PPH911+G6ur0PjXfsrUYP5pmZIcSHNzAbmjp3i4Gt53mIzO1mWkMX04OqISdxSNM/71f1BFFobAU1FJSkl6VbXr5xxc1Cwc2iHRiivsFVAa+FkIkdXmXJhdU2OOEUvdirkR2Ux0BCAiu+QQDC02hjtV5cXwq7IHA246AxlYlfNLBmLW1CLxJiuvztwmr09RniIVrQZmzmB96Z8hyXaeSTbCL6xCGLyHZSczEq7OsInVCFLVeVM7Syz2JeTAZXKx1OhJk3LM7AQ7szonj4=
  file: jam-box.zip
  skip_cleanup: true
  on:
    repo: delucis/jam-box
    tags: true
