os: osx
language: node_js
node_js:
- '6'
before_install:
- brew update && brew install git-lfs
- git lfs install
install:
- npm install
before_script:
- git lfs pull
script:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: LXDIErYYc3youTukgGL10bpBPaTbI8vGqUTJcWWrIvvuqxcXptz3DyniY/V69LVvxaAR8ULQe3jG2A8EWe74hS6XqWi6BYYA6JInnge2RnXKWSGHLZUHV8YbwIKdc1mva7TuKxIeFxdWlMgnNS2zcbLtQRFC9P3eKOhZYVdu6KaMyTVX67gcyW+WtdE7sAvKw/BRd57OOXgkaah1i0ZmErHPdBgQc/Fza+xH3Lk8SEg4a1NWRpyitRWMXjxtE/bxDu7r1OixKgvdJJygaTPRlbFzZa0lBmhwMfTVJkyIc/YRZ4wyHtH+dZz2oEijQSXjiKI43Ohe+YPHqpOdjrPyDJqI+azquJ6nj5eLrXa+u+gUe9ha13eQOsREMBchdcoXqgqkU9e91cvpKFiIV82AZEyLDCE6svczSnPV1NrWnSvOCs5sWmPYAQEh0STvt4xfoKIj/fYQa2GGZ4jXlbdL25EY56FS8JBHuoUSZrBQEcby5nXrowXEYlocdS+n0NsdjJOjSNge1PsaNdAlQQJhjgEYu+qpdjbFa6KDvPS2Bz+HCeJRIaMxU4unVNI6kXOi7JMvJyfQaLrQAy+GnNkBz9gqC72UOywO3ueHn+SF1xlDEHBRLykS7DnZp1AFlMvK9Bhidl27Q0bigxzZqtrEGlKKm5v4moWq5qVqz7JOhTk=
  file: jam-box.zip
  skip_cleanup: true
  on:
    repo: delucis/jam-box
    tags: true
