os: osx
language: node_js
node_js:
- '6'
before_install:
- brew update && brew install git-lfs
- git lfs install
install:
- npm install
before_script:
- git lfs pull
script:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: gcUFcWbj0HyQ7gcUz48qp6r/dOB8Jd/8Vnmx5/OYFMiSOpUiTPTJFf8NaVWRSR4jVvBbumtTbBBb9Kfq34vntkE+M5eAfp+7uhD002JHAYcfstqipVbDzMw5L4jmgMfp311U/M6GRuhCZsEzvCXIBAt+g7RH9MhFFbJm/CoJETSnew5IxPbKM1j3fD183vYJjONVhSTFUEzEHYxNTG1xnoURuudBJXdh1e7AERwZTS+bvROI6EN106kuSnqh9bIO88+PBtBqeXSIj+GTl+t+P/KreMHVxm9L3w/XD+oqLS7ZEOGKK80pySgn3VoOfQs2WECXtbrjHgWc9bb8K7sP1T/v77Rkh+HYeI4ENxV4lCC8DR5sOwpuI+nDmtutJJEJYm5EtSoErZZcak1pgm3AmM/djFOQRT42PIlFXdPlSz0j02LcCpUHVpDSTwUmYGCBqq41aeqkzWg2if3yBigGhjC5KEItvW2CZETGKq+uQRNV/y2CVwTQ5vahXS1qVQkrkXwsEdyTaaaIIgI/P1gKiTse4NnBRFIBXaoLcnepuZWiG2Stnd97eIyJArymZf3COnHWP3V24TGORliYwiJaWDp0pm6b/hY/N7ME0VOMjmsQc3lV51bsQHFfNhiqsQkQXFDz2EHj+R7qhhHg1L0NeqDumgGFtsRqDVq3vUXAKaU=
  file: jam-box.zip
  skip_cleanup: true
  on:
    repo: delucis/jam-box
    tags: true
